-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 15:52:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Glogiciels
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Glogiciels
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Glogiciels` DEFAULT CHARACTER SET utf8 ;
USE `Glogiciels` ;

-- -----------------------------------------------------
-- Table `Glogiciels`.`Developpeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Glogiciels`.`Developpeur` (
  `NumDev` INT NOT NULL,
  `NomDev` VARCHAR(45) NOT NULL,
  `AdrDev` VARCHAR(45) NOT NULL,
  `Emaildev` VARCHAR(45) NOT NULL,
  `TelDev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NumDev`),
  UNIQUE INDEX `NumDev_UNIQUE` (`NumDev` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Glogiciels`.`Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Glogiciels`.`Projet` (
  `NumProj` INT NOT NULL,
  `TitreProj` VARCHAR(45) NOT NULL,
  `DateDeb` DATE NOT NULL,
  `DateFin` DATE NOT NULL,
  PRIMARY KEY (`NumProj`),
  UNIQUE INDEX `NumProj_UNIQUE` (`NumProj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Glogiciels`.`Logiciel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Glogiciels`.`Logiciel` (
  `CodLog` INT NOT NULL,
  `NomLog` VARCHAR(45) NOT NULL,
  `PrixLog` VARCHAR(45) NOT NULL,
  `Projet_NumProj` INT NOT NULL,
  PRIMARY KEY (`CodLog`, `Projet_NumProj`),
  UNIQUE INDEX `CodLog_UNIQUE` (`CodLog` ASC) VISIBLE,
  INDEX `fk_Logiciel_Projet_idx` (`Projet_NumProj` ASC) VISIBLE,
  CONSTRAINT `fk_Logiciel_Projet`
    FOREIGN KEY (`Projet_NumProj`)
    REFERENCES `Glogiciels`.`Projet` (`NumProj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Glogiciels`.`Developpeur_has_Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Glogiciels`.`Developpeur_has_Projet` (
  `Developpeur_NumDev` INT NOT NULL,
  `Projet_NumProj` INT NOT NULL,
  PRIMARY KEY (`Developpeur_NumDev`, `Projet_NumProj`),
  INDEX `fk_Developpeur_has_Projet_Projet1_idx` (`Projet_NumProj` ASC) VISIBLE,
  INDEX `fk_Developpeur_has_Projet_Developpeur1_idx` (`Developpeur_NumDev` ASC) VISIBLE,
  CONSTRAINT `fk_Developpeur_has_Projet_Developpeur1`
    FOREIGN KEY (`Developpeur_NumDev`)
    REFERENCES `Glogiciels`.`Developpeur` (`NumDev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Developpeur_has_Projet_Projet1`
    FOREIGN KEY (`Projet_NumProj`)
    REFERENCES `Glogiciels`.`Projet` (`NumProj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
